### ISSUE TITLE
As a Cooper user, I want to view a skeleton of the role review cards while the data is being fetched so that the experience is seamless and uninterrupted.

### ISSUE THREAD

**Issue by RishikeshNK** [sandboxnu/cooper#51]
As the number of roles in the database increases, the time taken to fetch all of the roles will also increase. This will affect the load time of `/role`. Therefore, it is necessary to utilize [Loading UI and Streaming](https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming) (`loading.tsx`) to render a skeleton while the data is being fetched.

**Comment by joshw2048** [comment]
btw @RishikeshNK i think we can do away with the user stories lol, i used to like them cuz it's helpful for deciding direction of the project but my brain hurts reading my own stories

**Comment by RishikeshNK** [comment]
Bro switched from being a PM to being a SWE and started hating user stories 😹

**Comment by joshw2048** [comment]
Technically covered by #95
